name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - name: Build MkDocs site
        run: mkdocs build


      - name: Deploy to gh-pages (no force)
        run: |
          git fetch origin gh-pages
          git branch gh-pages origin/gh-pages
          git worktree add gh-pages-temp gh-pages

          rsync -av --delete --exclude=.git site/ gh-pages-temp/
          touch gh-pages-temp/.nojekyll

          cd gh-pages-temp
          git add .
          git commit -m "Update docs [skip ci]" || echo "No changes"
          git push origin gh-pages
          cd ..
          git worktree remove gh-pages-temp